#!/usr/bin/perl
use warnings;
print("enter the password:");
chomp($pos=<>);
if($pos=~ m/^[a-zA-Z]([0-9]|[@#$%^&*])*[a-z-A-Z0-9_]$/){
     print"the password is valid:$pos\n";
}
else{
   print"password is not valid:$pos\n";
}
